site_name: QuickServer Documents
theme: readthedocs

markdown_extensions: [extra, codehilite, headerid]
use_directory_urls: false

pages:
- [index.md, Home]
- [intro.md, 介绍]
- [install.md, 安装 Quick Server]
- [config.md, 配置 Quick Server]
- [admin.md, 管理接口]
- [changelog.md, Change Log]
- [license.md, License]
